-- Offline <-> Online Sync Phase O2A: schema verification + sync safety
-- foundation. This migration does NOT implement offline storage or
-- synchronization -- it only adds the minimum backend primitives a future
-- offline outbox will need: a revision counter for stale-write detection,
-- an idempotency ledger for safe replay, and validated write-path RPCs
-- that enforce both.
--
-- Live schema verified against the linked project (information_schema /
-- pg_catalog) before writing this migration -- see the O2A report for the
-- full verification output. Notable confirmed facts that shape this file:
--   - patients.id is `generated always as identity` (bigint) -- callers
--     never supply it; patient_create() below relies purely on the
--     column default.
--   - consultation_id / followup_id / initialconsultation_id / vitals_id
--     are all `generated by default as identity` (bigint).
--   - patient_consent already has a `unique (patient_id)` constraint --
--     out of scope for O2A (not one of the four listed sync-eligible
--     tables), left untouched.
--   - guard_consultation_integrity(), guard_follow_up_integrity(), and
--     guard_initial_consultation_visit_disposition() all do whole-row
--     jsonb diffs excluding a fixed column list to enforce "only these
--     fields may change". The new revision/updated_at columns are NOT in
--     those excluded-column lists, so the new bump-revision trigger on
--     each table is named to fire alphabetically AFTER the existing
--     guard trigger (prefixed zz_) -- by the time the guard trigger
--     inspects NEW, revision/updated_at are still unchanged (a plain
--     client UPDATE never sets them), so no existing guard is tripped.
--     Only after the guard passes does this migration's trigger bump
--     revision/updated_at. This avoids touching the existing guard
--     function bodies at all.

-- ============================================================
-- 1. Shared revision/updated_at columns + trigger
-- ============================================================

alter table public.patients
  add column if not exists revision integer not null default 1,
  add column if not exists updated_at timestamptz not null default now();

alter table public.consultation
  add column if not exists revision integer not null default 1,
  add column if not exists updated_at timestamptz not null default now();

alter table public.follow_up
  add column if not exists revision integer not null default 1,
  add column if not exists updated_at timestamptz not null default now();

alter table public.initial_consultation
  add column if not exists revision integer not null default 1,
  add column if not exists updated_at timestamptz not null default now();

-- One shared trigger function (generalizes the existing bespoke
-- fhsis_set_updated_at() pattern). UPDATE-only by design -- INSERT
-- defaults (revision=1, updated_at=now()) already cover row creation, so
-- this function is never attached to a BEFORE INSERT trigger and never
-- touches inserts. Only bumps when the row's *other* columns actually
-- changed (a resubmitted, content-identical UPDATE does not consume a
-- revision), which matters for retried/replayed writes.
create or replace function public.bump_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (to_jsonb(new) - 'revision' - 'updated_at') is distinct from (to_jsonb(old) - 'revision' - 'updated_at') then
    new.revision := old.revision + 1;
    new.updated_at := now();
  else
    new.revision := old.revision;
    new.updated_at := old.updated_at;
  end if;
  return new;
end;
$$;

revoke all on function public.bump_revision() from public, anon, authenticated;

-- Trigger names prefixed zz_ so they fire after any existing guard
-- trigger on the same table (Postgres fires same-timing triggers in name
-- order). Confirmed via live pg_catalog inspection that none of these
-- four tables already had an updated_at/revision-style trigger, so there
-- is no double-increment risk to guard against.
drop trigger if exists zz_bump_revision on public.patients;
create trigger zz_bump_revision
  before update on public.patients
  for each row execute function public.bump_revision();

drop trigger if exists zz_bump_revision on public.consultation;
create trigger zz_bump_revision
  before update on public.consultation
  for each row execute function public.bump_revision();

drop trigger if exists zz_bump_revision on public.follow_up;
create trigger zz_bump_revision
  before update on public.follow_up
  for each row execute function public.bump_revision();

drop trigger if exists zz_bump_revision on public.initial_consultation;
create trigger zz_bump_revision
  before update on public.initial_consultation
  for each row execute function public.bump_revision();

-- ============================================================
-- 2. Idempotency ledger
-- ============================================================
-- Deliberately minimal -- no clinical payload is stored here, only the
-- small structured `result` a replayed call should return verbatim.
-- RLS is enabled with zero grants/policies for ordinary roles, so this
-- table is reachable only from SECURITY DEFINER functions (which run as
-- the table owner and bypass RLS) -- no direct client select/insert is
-- possible, preventing spoofing or cross-actor reads of unrelated
-- operations.
create table if not exists public.applied_operations (
  operation_id uuid primary key,
  entity_type text not null check (entity_type in ('patient', 'initial_consultation', 'consultation', 'follow_up')),
  operation_type text not null check (operation_type in ('create', 'update')),
  actor_id uuid not null references auth.users(id),
  server_record_id bigint,
  result jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.applied_operations enable row level security;
revoke all on public.applied_operations from public, anon, authenticated;

-- ============================================================
-- 3. Conflict-safe write paths
-- ============================================================
-- All four RPCs below share the same outcome contract so future sync
-- code never has to parse a generic Postgres exception to know what
-- happened:
--   {"outcome": "success", "serverId": ..., "revision": ...}
--   {"outcome": "already_applied", ...same shape as the original success result}
--   {"outcome": "conflict", "currentRevision": ...}          -- UPDATE only
--   {"outcome": "invalid_transition", "message": "..."}      -- a guard/trigger rejected the write
--   {"outcome": "unauthorized"}
--   {"outcome": "validation_failed", "message": "..."}
-- None of these are raised as bare exceptions -- every expected failure
-- mode returns a normal jsonb value the caller can branch on. Role
-- checks mirror the existing RLS policies exactly (defense in depth,
-- same convention as record_initial_intake); RLS itself is unchanged and
-- remains the real enforcement boundary since these functions still only
-- ever act as the calling user's own identity (auth.uid()), never a
-- service-role bypass.

-- ---- 3a. Patient CREATE / UPDATE ----

create or replace function public.patient_create(p_operation_id uuid, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_existing public.applied_operations%rowtype;
  v_id bigint;
  v_result jsonb;
begin
  if p_operation_id is null then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'operationId is required');
  end if;

  select p.role into v_role from public.profiles p where p.id = (select auth.uid());
  if coalesce(v_role, '') not in ('doctor', 'nurse', 'BHW') then
    return jsonb_build_object('outcome', 'unauthorized');
  end if;

  select * into v_existing from public.applied_operations
  where operation_id = p_operation_id and entity_type = 'patient' and operation_type = 'create';
  if found then
    return v_existing.result || jsonb_build_object('outcome', 'already_applied');
  end if;

  begin
    insert into public.patients (
      "firstName", "middleName", "lastName", suffix, age, sex, "civilStatus", birthday, nationality,
      "bloodType", religion, "birthPlace", address, "contactNumber", "educationalAttain", "employmentStatus",
      "philhealthNo", "philhealthStatus", category, "categoryOthers", "relativeName", "relativeRelation",
      "relativeAddress", "relativeContact"
    ) values (
      p_payload->>'firstName', p_payload->>'middleName', p_payload->>'lastName', p_payload->>'suffix',
      nullif(p_payload->>'age', '')::bigint, p_payload->>'sex', p_payload->>'civilStatus', p_payload->>'birthday',
      p_payload->>'nationality', p_payload->>'bloodType', p_payload->>'religion', p_payload->>'birthPlace',
      p_payload->>'address', nullif(p_payload->>'contactNumber', '')::bigint, p_payload->>'educationalAttain',
      p_payload->>'employmentStatus', p_payload->>'philhealthNo', p_payload->>'philhealthStatus',
      p_payload->>'category', p_payload->>'categoryOthers', p_payload->>'relativeName', p_payload->>'relativeRelation',
      p_payload->>'relativeAddress', p_payload->>'relativeContact'
    )
    returning id into v_id;
  exception when others then
    return jsonb_build_object('outcome', 'validation_failed', 'message', sqlerrm);
  end;

  v_result := jsonb_build_object('outcome', 'success', 'serverId', v_id, 'revision', 1);

  insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
  values (p_operation_id, 'patient', 'create', (select auth.uid()), v_id, v_result);

  return v_result;
end;
$$;

revoke all on function public.patient_create(uuid, jsonb) from public, anon;
grant execute on function public.patient_create(uuid, jsonb) to authenticated;

create or replace function public.patient_update(p_operation_id uuid, p_patient_id bigint, p_base_revision integer, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_existing public.applied_operations%rowtype;
  v_current_revision integer;
  v_new_revision integer;
  v_set text := '';
  v_key text;
  v_allowed text[] := array[
    'firstName', 'middleName', 'lastName', 'suffix', 'age', 'sex', 'civilStatus', 'birthday', 'nationality',
    'bloodType', 'religion', 'birthPlace', 'address', 'contactNumber', 'educationalAttain', 'employmentStatus',
    'philhealthNo', 'philhealthStatus', 'category', 'categoryOthers', 'relativeName', 'relativeRelation',
    'relativeAddress', 'relativeContact'
  ];
  v_result jsonb;
begin
  if p_operation_id is null then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'operationId is required');
  end if;

  select p.role into v_role from public.profiles p where p.id = (select auth.uid());
  if coalesce(v_role, '') not in ('BHW', 'nurse', 'doctor', 'midwives') then
    return jsonb_build_object('outcome', 'unauthorized');
  end if;

  select * into v_existing from public.applied_operations
  where operation_id = p_operation_id and entity_type = 'patient' and operation_type = 'update';
  if found then
    return v_existing.result || jsonb_build_object('outcome', 'already_applied');
  end if;

  select revision into v_current_revision from public.patients where id = p_patient_id for update;
  if not found then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'patient not found');
  end if;

  if v_current_revision is distinct from p_base_revision then
    return jsonb_build_object('outcome', 'conflict', 'currentRevision', v_current_revision);
  end if;

  for v_key in select jsonb_object_keys(p_payload) loop
    if v_key = any(v_allowed) then
      v_set := v_set || format('%I = %L, ', v_key, p_payload->>v_key);
    end if;
  end loop;

  if v_set = '' then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'no updatable fields provided');
  end if;
  v_set := left(v_set, length(v_set) - 2);

  begin
    execute format('update public.patients set %s where id = %L', v_set, p_patient_id);
  exception when others then
    return jsonb_build_object('outcome', 'invalid_transition', 'message', sqlerrm);
  end;

  select revision into v_new_revision from public.patients where id = p_patient_id;
  v_result := jsonb_build_object('outcome', 'success', 'serverId', p_patient_id, 'revision', v_new_revision);

  insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
  values (p_operation_id, 'patient', 'update', (select auth.uid()), p_patient_id, v_result);

  return v_result;
end;
$$;

revoke all on function public.patient_update(uuid, bigint, integer, jsonb) from public, anon;
grant execute on function public.patient_update(uuid, bigint, integer, jsonb) to authenticated;

-- ---- 3b. Initial consultation + vitals (extend, don't replace) ----
-- record_initial_intake's signature grows an optional trailing
-- parameter, so every existing caller (which never passes it) keeps
-- returning a bare bigint exactly as before -- true backward
-- compatibility, not just "the new default happens to match old
-- behavior". Only when p_operation_id is supplied does idempotency
-- bookkeeping activate at all; a null operation id (today's only caller)
-- skips the applied_operations table entirely, identical to pre-O2A
-- behavior.
-- CREATE OR REPLACE cannot widen a function's signature in place --
-- Postgres treats (jsonb, jsonb) and (jsonb, jsonb, uuid) as distinct
-- overloads, which would leave BOTH versions callable and break
-- PostgREST's RPC dispatch (it cannot disambiguate an ambiguous 2-arg
-- call once a 3-arg overload also matches by name). The original
-- 2-argument function must be dropped first so the 3-argument version
-- with a default becomes the only overload -- this is what actually
-- preserves "existing callers who never pass p_operation_id keep
-- working unchanged", not merely giving the new parameter a default.
drop function if exists public.record_initial_intake(jsonb, jsonb);

create or replace function public.record_initial_intake(p_initial jsonb, p_vitals jsonb, p_operation_id uuid default null)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_patient_id public.patients.id%type;
  v_vitals_patient_id public.patients.id%type;
  v_initial_consultation_id bigint;
  v_existing public.applied_operations%rowtype;
begin
  select p.role
  into v_role
  from public.profiles p
  where p.id = (select auth.uid());

  if coalesce(v_role, '') not in ('nurse', 'midwives') then
    raise exception 'Initial intake is restricted to nurses and midwives' using errcode = '42501';
  end if;

  if p_operation_id is not null then
    select * into v_existing from public.applied_operations
    where operation_id = p_operation_id and entity_type = 'initial_consultation' and operation_type = 'create';
    if found then
      return (v_existing.result->>'serverId')::bigint;
    end if;
  end if;

  v_patient_id := p_initial ->> 'patient_id';
  v_vitals_patient_id := p_vitals ->> 'patient_id';

  if v_patient_id is null or v_vitals_patient_id is distinct from v_patient_id then
    raise exception 'Initial intake and vital signs must reference the same patient';
  end if;

  if not exists (
    select 1 from public.patients p where p.id = v_patient_id
  ) then
    raise exception 'Initial intake requires a valid patient';
  end if;

  insert into public.initial_consultation (
    patient_id,
    consultation_date,
    consultation_time,
    mode_of_transaction,
    referred_by,
    mode_of_transfer,
    chief_complaint,
    diagnosis,
    visit_disposition
  ) values (
    v_patient_id,
    p_initial ->> 'consultation_date',
    p_initial ->> 'consultation_time',
    p_initial ->> 'mode_of_transaction',
    p_initial ->> 'referred_by',
    p_initial ->> 'mode_of_transfer',
    p_initial ->> 'chief_complaint',
    p_initial ->> 'diagnosis',
    p_initial ->> 'visit_disposition'
  )
  returning initialconsultation_id into v_initial_consultation_id;

  insert into public.vital_sign (
    patient_id,
    initial_consultation_id,
    bp,
    heart_rate,
    respiratory_rate,
    temperature,
    o2_saturation,
    weight,
    height,
    nutritional_status,
    bmi,
    visual_acuity_left,
    visual_acuity_right,
    general_survey
  ) values (
    v_patient_id,
    v_initial_consultation_id,
    p_vitals ->> 'bp',
    nullif(p_vitals ->> 'heart_rate', '')::numeric,
    nullif(p_vitals ->> 'respiratory_rate', '')::numeric,
    nullif(p_vitals ->> 'temperature', '')::numeric,
    nullif(p_vitals ->> 'o2_saturation', '')::numeric,
    nullif(p_vitals ->> 'weight', '')::numeric,
    nullif(p_vitals ->> 'height', '')::numeric,
    p_vitals ->> 'nutritional_status',
    nullif(p_vitals ->> 'bmi', '')::numeric,
    p_vitals ->> 'visual_acuity_left',
    p_vitals ->> 'visual_acuity_right',
    p_vitals ->> 'general_survey'
  );

  if p_operation_id is not null then
    insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
    values (
      p_operation_id, 'initial_consultation', 'create', (select auth.uid()), v_initial_consultation_id,
      jsonb_build_object('outcome', 'success', 'serverId', v_initial_consultation_id, 'revision', 1)
    );
  end if;

  return v_initial_consultation_id;
end;
$$;

-- New, separate RPC for the disposition-correction path (today a direct
-- client UPDATE under the existing initial_consultation_update_visit_
-- disposition[_midwife] RLS policies). This RPC is additive -- those RLS
-- policies are untouched, so the existing direct-update path keeps
-- working unchanged; this RPC is simply the new, revision-checked way to
-- do the same thing once a future offline queue needs it.
create or replace function public.initial_consultation_update_disposition(
  p_operation_id uuid,
  p_initial_consultation_id bigint,
  p_base_revision integer,
  p_visit_disposition text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_existing public.applied_operations%rowtype;
  v_current_revision integer;
  v_new_revision integer;
  v_result jsonb;
begin
  if p_operation_id is null then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'operationId is required');
  end if;

  select p.role into v_role from public.profiles p where p.id = (select auth.uid());
  if coalesce(v_role, '') not in ('nurse', 'midwives') then
    return jsonb_build_object('outcome', 'unauthorized');
  end if;

  select * into v_existing from public.applied_operations
  where operation_id = p_operation_id and entity_type = 'initial_consultation' and operation_type = 'update';
  if found then
    return v_existing.result || jsonb_build_object('outcome', 'already_applied');
  end if;

  select revision into v_current_revision from public.initial_consultation where initialconsultation_id = p_initial_consultation_id for update;
  if not found then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'initial consultation not found');
  end if;

  if v_current_revision is distinct from p_base_revision then
    return jsonb_build_object('outcome', 'conflict', 'currentRevision', v_current_revision);
  end if;

  begin
    update public.initial_consultation
    set visit_disposition = p_visit_disposition
    where initialconsultation_id = p_initial_consultation_id;
  exception when others then
    return jsonb_build_object('outcome', 'invalid_transition', 'message', sqlerrm);
  end;

  select revision into v_new_revision from public.initial_consultation where initialconsultation_id = p_initial_consultation_id;
  v_result := jsonb_build_object('outcome', 'success', 'serverId', p_initial_consultation_id, 'revision', v_new_revision);

  insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
  values (p_operation_id, 'initial_consultation', 'update', (select auth.uid()), p_initial_consultation_id, v_result);

  return v_result;
end;
$$;

revoke all on function public.record_initial_intake(jsonb, jsonb, uuid) from public, anon;
grant execute on function public.record_initial_intake(jsonb, jsonb, uuid) to authenticated;
revoke all on function public.initial_consultation_update_disposition(uuid, bigint, integer, text) from public, anon;
grant execute on function public.initial_consultation_update_disposition(uuid, bigint, integer, text) to authenticated;

-- ---- 3c. Consultation CREATE / UPDATE ----

create or replace function public.consultation_create(p_operation_id uuid, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_existing public.applied_operations%rowtype;
  v_id bigint;
  v_result jsonb;
begin
  if p_operation_id is null then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'operationId is required');
  end if;

  select p.role into v_role from public.profiles p where p.id = (select auth.uid());
  if coalesce(v_role, '') <> 'doctor' then
    return jsonb_build_object('outcome', 'unauthorized');
  end if;

  select * into v_existing from public.applied_operations
  where operation_id = p_operation_id and entity_type = 'consultation' and operation_type = 'create';
  if found then
    return v_existing.result || jsonb_build_object('outcome', 'already_applied');
  end if;

  begin
    insert into public.consultation (
      patient_id, initial_consultation_id, attending_provider,
      family_history, immunization_history, smoking_status, smoking_sticks_per_day, smoking_years,
      drinking_status, drinking_frequency, drinking_years, menarche_age, sexual_onset_age, is_menopause,
      menopause_age, lmp, interval_cycle, period_duration, pads_per_day, birth_control_method,
      gravidity, parity, delivery_type, full_term_count, premature_count, abortion_count,
      living_children_count, pre_eclampsia, medication_treatment, management_treatment,
      chief_complaints, diagnosis, hpi, assessment, plan, past_med_surg_history,
      history_present_illness, follow_up_status
    ) values (
      nullif(p_payload->>'patient_id', '')::bigint,
      nullif(p_payload->>'initial_consultation_id', '')::bigint,
      p_payload->>'attending_provider',
      p_payload->>'family_history', p_payload->>'immunization_history', p_payload->>'smoking_status',
      nullif(p_payload->>'smoking_sticks_per_day', '')::bigint, nullif(p_payload->>'smoking_years', '')::bigint,
      p_payload->>'drinking_status', p_payload->>'drinking_frequency', nullif(p_payload->>'drinking_years', '')::bigint,
      nullif(p_payload->>'menarche_age', '')::bigint, nullif(p_payload->>'sexual_onset_age', '')::bigint,
      p_payload->>'is_menopause', nullif(p_payload->>'menopause_age', '')::bigint, p_payload->>'lmp',
      p_payload->>'interval_cycle', p_payload->>'period_duration', nullif(p_payload->>'pads_per_day', '')::bigint,
      p_payload->>'birth_control_method', nullif(p_payload->>'gravidity', '')::bigint, nullif(p_payload->>'parity', '')::bigint,
      p_payload->>'delivery_type', nullif(p_payload->>'full_term_count', '')::bigint, nullif(p_payload->>'premature_count', '')::bigint,
      nullif(p_payload->>'abortion_count', '')::bigint, nullif(p_payload->>'living_children_count', '')::bigint,
      p_payload->>'pre_eclampsia', p_payload->>'medication_treatment', p_payload->>'management_treatment',
      p_payload->>'chief_complaints', p_payload->>'diagnosis', p_payload->>'hpi', p_payload->>'assessment', p_payload->>'plan',
      p_payload->>'past_med_surg_history', p_payload->>'history_present_illness',
      coalesce(p_payload->>'follow_up_status', 'pending')
    )
    returning consultation_id into v_id;
  exception when others then
    return jsonb_build_object('outcome', 'validation_failed', 'message', sqlerrm);
  end;

  v_result := jsonb_build_object('outcome', 'success', 'serverId', v_id, 'revision', 1);

  insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
  values (p_operation_id, 'consultation', 'create', (select auth.uid()), v_id, v_result);

  return v_result;
end;
$$;

revoke all on function public.consultation_create(uuid, jsonb) from public, anon;
grant execute on function public.consultation_create(uuid, jsonb) to authenticated;

create or replace function public.consultation_update(p_operation_id uuid, p_consultation_id bigint, p_base_revision integer, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_existing public.applied_operations%rowtype;
  v_current_revision integer;
  v_new_revision integer;
  v_set text := '';
  v_key text;
  -- Deliberately excludes patient_id / initial_consultation_id /
  -- attending_provider -- guard_consultation_integrity already makes
  -- these immutable on UPDATE, so they are never offered here either.
  v_allowed text[] := array[
    'family_history', 'immunization_history', 'smoking_status', 'smoking_sticks_per_day', 'smoking_years',
    'drinking_status', 'drinking_frequency', 'drinking_years', 'menarche_age', 'sexual_onset_age', 'is_menopause',
    'menopause_age', 'lmp', 'interval_cycle', 'period_duration', 'pads_per_day', 'birth_control_method',
    'gravidity', 'parity', 'delivery_type', 'full_term_count', 'premature_count', 'abortion_count',
    'living_children_count', 'pre_eclampsia', 'medication_treatment', 'management_treatment',
    'chief_complaints', 'diagnosis', 'hpi', 'assessment', 'plan'
  ];
  v_result jsonb;
begin
  if p_operation_id is null then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'operationId is required');
  end if;

  select p.role into v_role from public.profiles p where p.id = (select auth.uid());
  if coalesce(v_role, '') <> 'doctor' then
    return jsonb_build_object('outcome', 'unauthorized');
  end if;

  select * into v_existing from public.applied_operations
  where operation_id = p_operation_id and entity_type = 'consultation' and operation_type = 'update';
  if found then
    return v_existing.result || jsonb_build_object('outcome', 'already_applied');
  end if;

  select revision into v_current_revision from public.consultation where consultation_id = p_consultation_id for update;
  if not found then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'consultation not found');
  end if;

  if v_current_revision is distinct from p_base_revision then
    return jsonb_build_object('outcome', 'conflict', 'currentRevision', v_current_revision);
  end if;

  for v_key in select jsonb_object_keys(p_payload) loop
    if v_key = any(v_allowed) then
      v_set := v_set || format('%I = %L, ', v_key, p_payload->>v_key);
    end if;
  end loop;

  if v_set = '' then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'no updatable fields provided');
  end if;
  v_set := left(v_set, length(v_set) - 2);

  begin
    execute format('update public.consultation set %s where consultation_id = %L', v_set, p_consultation_id);
  exception when others then
    return jsonb_build_object('outcome', 'invalid_transition', 'message', sqlerrm);
  end;

  select revision into v_new_revision from public.consultation where consultation_id = p_consultation_id;
  v_result := jsonb_build_object('outcome', 'success', 'serverId', p_consultation_id, 'revision', v_new_revision);

  insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
  values (p_operation_id, 'consultation', 'update', (select auth.uid()), p_consultation_id, v_result);

  return v_result;
end;
$$;

revoke all on function public.consultation_update(uuid, bigint, integer, jsonb) from public, anon;
grant execute on function public.consultation_update(uuid, bigint, integer, jsonb) to authenticated;

-- ---- 3d. Follow-up CREATE / UPDATE ----

create or replace function public.follow_up_create(p_operation_id uuid, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_existing public.applied_operations%rowtype;
  v_id bigint;
  v_result jsonb;
begin
  if p_operation_id is null then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'operationId is required');
  end if;

  select p.role into v_role from public.profiles p where p.id = (select auth.uid());
  if coalesce(v_role, '') <> 'doctor' then
    return jsonb_build_object('outcome', 'unauthorized');
  end if;

  select * into v_existing from public.applied_operations
  where operation_id = p_operation_id and entity_type = 'follow_up' and operation_type = 'create';
  if found then
    return v_existing.result || jsonb_build_object('outcome', 'already_applied');
  end if;

  begin
    insert into public.follow_up (
      patient_id, consultation_id, visit_date, visit_time, mode_of_transaction, mode_of_transfer,
      chief_complaint, diagnosis, history_of_present_illness, bp, heart_rate, respiratory_rate,
      temperature, o2_saturation, weight, height, muac, nutritional_status, bmi,
      visual_acuity_left, visual_acuity_right, blood_type, general_survey, medication_treatment,
      lab_results, signature_url, follow_up_status
    ) values (
      nullif(p_payload->>'patient_id', '')::bigint, nullif(p_payload->>'consultation_id', '')::bigint,
      p_payload->>'visit_date', p_payload->>'visit_time', p_payload->>'mode_of_transaction', p_payload->>'mode_of_transfer',
      p_payload->>'chief_complaint', p_payload->>'diagnosis', p_payload->>'history_of_present_illness',
      p_payload->>'bp', nullif(p_payload->>'heart_rate', '')::bigint, nullif(p_payload->>'respiratory_rate', '')::bigint,
      nullif(p_payload->>'temperature', '')::double precision, nullif(p_payload->>'o2_saturation', '')::bigint,
      nullif(p_payload->>'weight', '')::double precision, nullif(p_payload->>'height', '')::double precision,
      nullif(p_payload->>'muac', '')::double precision, p_payload->>'nutritional_status',
      nullif(p_payload->>'bmi', '')::double precision, p_payload->>'visual_acuity_left', p_payload->>'visual_acuity_right',
      p_payload->>'blood_type', p_payload->>'general_survey', p_payload->>'medication_treatment',
      p_payload->>'lab_results', p_payload->>'signature_url', coalesce(p_payload->>'follow_up_status', 'pending')
    )
    returning followup_id into v_id;
  exception when others then
    return jsonb_build_object('outcome', 'validation_failed', 'message', sqlerrm);
  end;

  v_result := jsonb_build_object('outcome', 'success', 'serverId', v_id, 'revision', 1);

  insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
  values (p_operation_id, 'follow_up', 'create', (select auth.uid()), v_id, v_result);

  return v_result;
end;
$$;

revoke all on function public.follow_up_create(uuid, jsonb) from public, anon;
grant execute on function public.follow_up_create(uuid, jsonb) to authenticated;

create or replace function public.follow_up_update(p_operation_id uuid, p_followup_id bigint, p_base_revision integer, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_existing public.applied_operations%rowtype;
  v_current_revision integer;
  v_new_revision integer;
  v_set text := '';
  v_key text;
  -- Excludes patient_id / consultation_id (immutable per
  -- guard_follow_up_integrity). follow_up_status IS included -- the
  -- guard trigger itself still refuses to change it once 'done', so an
  -- attempt to do so via this RPC surfaces as outcome:invalid_transition
  -- rather than silently failing.
  v_allowed text[] := array[
    'visit_date', 'visit_time', 'mode_of_transaction', 'mode_of_transfer', 'chief_complaint', 'diagnosis',
    'history_of_present_illness', 'bp', 'heart_rate', 'respiratory_rate', 'temperature', 'o2_saturation',
    'weight', 'height', 'muac', 'nutritional_status', 'bmi', 'visual_acuity_left', 'visual_acuity_right',
    'blood_type', 'general_survey', 'medication_treatment', 'lab_results', 'signature_url', 'follow_up_status'
  ];
  v_result jsonb;
begin
  if p_operation_id is null then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'operationId is required');
  end if;

  select p.role into v_role from public.profiles p where p.id = (select auth.uid());
  if coalesce(v_role, '') <> 'doctor' then
    return jsonb_build_object('outcome', 'unauthorized');
  end if;

  select * into v_existing from public.applied_operations
  where operation_id = p_operation_id and entity_type = 'follow_up' and operation_type = 'update';
  if found then
    return v_existing.result || jsonb_build_object('outcome', 'already_applied');
  end if;

  select revision into v_current_revision from public.follow_up where followup_id = p_followup_id for update;
  if not found then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'follow-up not found');
  end if;

  if v_current_revision is distinct from p_base_revision then
    return jsonb_build_object('outcome', 'conflict', 'currentRevision', v_current_revision);
  end if;

  for v_key in select jsonb_object_keys(p_payload) loop
    if v_key = any(v_allowed) then
      v_set := v_set || format('%I = %L, ', v_key, p_payload->>v_key);
    end if;
  end loop;

  if v_set = '' then
    return jsonb_build_object('outcome', 'validation_failed', 'message', 'no updatable fields provided');
  end if;
  v_set := left(v_set, length(v_set) - 2);

  begin
    execute format('update public.follow_up set %s where followup_id = %L', v_set, p_followup_id);
  exception when others then
    return jsonb_build_object('outcome', 'invalid_transition', 'message', sqlerrm);
  end;

  select revision into v_new_revision from public.follow_up where followup_id = p_followup_id;
  v_result := jsonb_build_object('outcome', 'success', 'serverId', p_followup_id, 'revision', v_new_revision);

  insert into public.applied_operations (operation_id, entity_type, operation_type, actor_id, server_record_id, result)
  values (p_operation_id, 'follow_up', 'update', (select auth.uid()), p_followup_id, v_result);

  return v_result;
end;
$$;

revoke all on function public.follow_up_update(uuid, bigint, integer, jsonb) from public, anon;
grant execute on function public.follow_up_update(uuid, bigint, integer, jsonb) to authenticated;
